Repository byeong-chang/Stand_Up_Seoul, pull requests merged in 2023-06, with the labels that each got.

#9 gitflow-feature-stash: #8-requirements
  Documents/요구사항 정의서 및 WBS.xlsx
Labels: documentation

#11 Feature/#10 jpa db
  backend/src/main/java/com/project/backend/places/repository/ContentTypeRepository.java
  backend/src/main/java/com/project/backend/places/repository/CulturalEventRepository.java
  backend/src/main/java/com/project/backend/places/repository/DistrictRepository.java
  backend/src/main/java/com/project/backend/places/repository/HotplacesRepository.java
  backend/src/main/java/com/project/backend/places/repository/PlaceCategoryRepository.java
  backend/src/main/java/com/project/backend/places/repository/PlaceRepository.java
  backend/src/main/java/com/project/backend/places/repository/SubwayDetailRepository.java
  backend/src/main/java/com/project/backend/places/repository/SubwayRepository.java
  backend/src/main/java/com/project/backend/places/repository/entity/ContentType.java
  backend/src/main/java/com/project/backend/places/repository/entity/CulturalEvent.java
  backend/src/main/java/com/project/backend/places/repository/entity/District.java
  backend/src/main/java/com/project/backend/places/repository/entity/Hotplaces.java
  backend/src/main/java/com/project/backend/places/repository/entity/Place.java
  backend/src/main/java/com/project/backend/places/repository/entity/PlaceCategory.java
  backend/src/main/java/com/project/backend/places/repository/entity/Subway.java
  backend/src/main/java/com/project/backend/places/repository/entity/SubwayDetail.java
  backend/src/main/java/com/project/backend/population/repository/PopulationCongestMsgRepository.java
  backend/src/main/java/com/project/backend/population/repository/PopulationRepository.java
  backend/src/main/java/com/project/backend/population/repository/entity/Population.java
  backend/src/main/java/com/project/backend/population/repository/entity/PopulationCongestMsg.java
  backend/src/main/java/com/project/backend/restaurants/repository/RestaurantBreaktimeRepository.java
  backend/src/main/java/com/project/backend/restaurants/repository/RestaurantCategoryRepository.java
  backend/src/main/java/com/project/backend/restaurants/repository/RestaurantRepository.java
  backend/src/main/java/com/project/backend/restaurants/repository/RestaurantRuntimeRepository.java
  backend/src/main/java/com/project/backend/restaurants/repository/entity/Restaurant.java
  backend/src/main/java/com/project/backend/restaurants/repository/entity/RestaurantBreaktime.java
  backend/src/main/java/com/project/backend/restaurants/repository/entity/RestaurantCategory.java
  backend/src/main/java/com/project/backend/restaurants/repository/entity/RestaurantRuntime.java
  backend/src/main/java/com/project/backend/test/controller/CrudController.java
  backend/src/main/java/com/project/backend/test/entity/CrudEntity.java
  backend/src/main/java/com/project/backend/test/repository/CrudEntityRepository.java
  backend/src/main/java/com/project/backend/weather/repository/WeatherFcstRepository.java
  backend/src/main/java/com/project/backend/weather/repository/WeatherRepository.java
  backend/src/main/java/com/project/backend/weather/repository/entity/Weather.java
  backend/src/main/java/com/project/backend/weather/repository/entity/WeatherFcst.java
Labels: enhancement

#29 #28 - 스프링 부트와 리액트 연동하기
  backend/build.gradle
Labels: enhancement

#37 Feature/#30 login and signup
  backend/build.gradle
  backend/src/main/java/com/project/backend/BackendController.java
  backend/src/main/java/com/project/backend/SecurityConfig.java
  backend/src/main/java/com/project/backend/UserController.java
  backend/src/main/java/com/project/backend/accounts/entity/User.java
  backend/src/main/java/com/project/backend/accounts/repository/UserRepository.java
  backend/src/main/java/com/project/backend/accounts/service/UserService.java
Labels: enhancement

#39 #31-apiDtoTransfer
  backend/src/main/java/com/project/backend/controller/LiveType.java
  backend/src/main/java/com/project/backend/places/dto/CulturalEventDto.java
  backend/src/main/java/com/project/backend/places/dto/HotplacesDto.java
  backend/src/main/java/com/project/backend/places/dto/PlaceDistrictDto.java
  backend/src/main/java/com/project/backend/places/dto/PlaceDto.java
  backend/src/main/java/com/project/backend/places/dto/SubwayDto.java
  backend/src/main/java/com/project/backend/places/repository/entity/Hotplaces.java
  backend/src/main/java/com/project/backend/places/service/CulturalEventService.java
  backend/src/main/java/com/project/backend/places/service/CulturalEventServiceImpl.java
  backend/src/main/java/com/project/backend/places/service/HotPlacesService.java
  backend/src/main/java/com/project/backend/places/service/HotPlacesServiceImpl.java
  backend/src/main/java/com/project/backend/places/service/PlaceDistrictService.java
  backend/src/main/java/com/project/backend/places/service/PlaceDistrictServiceImpl.java
  backend/src/main/java/com/project/backend/places/service/PlaceService.java
  backend/src/main/java/com/project/backend/places/service/PlaceServiceImpl.java
  backend/src/main/java/com/project/backend/places/service/SubwayService.java
  backend/src/main/java/com/project/backend/places/service/SubwayServiceImpl.java
  backend/src/main/java/com/project/backend/population/dto/PopulationDto.java
  backend/src/main/java/com/project/backend/population/repository/PopulationRepository.java
  backend/src/main/java/com/project/backend/population/repository/entity/Population.java
  backend/src/main/java/com/project/backend/population/service/PopulationService.java
  backend/src/main/java/com/project/backend/population/service/PopulationServiceImpl.java
  backend/src/main/java/com/project/backend/restaurants/repository/dto/RestaurantDto.java
  backend/src/main/java/com/project/backend/restaurants/repository/entity/Restaurant.java
  backend/src/main/java/com/project/backend/restaurants/service/RestaurantService.java
  backend/src/main/java/com/project/backend/restaurants/service/RestaurantServiceImpl.java
Labels: enhancement

#48 #30 - 로그인 및 회원가입 기능 구현하기
  backend/src/main/java/com/project/backend/accounts/entity/MarketAdmin.java
  backend/src/main/java/com/project/backend/accounts/entity/RestaurantAdmin.java
  backend/src/main/java/com/project/backend/accounts/entity/RestaurantReview.java
  backend/src/main/java/com/project/backend/accounts/entity/User.java
  backend/src/main/java/com/project/backend/accounts/entity/Users.java
  backend/src/main/java/com/project/backend/accounts/repository/RestaurantAdminRepository.java
  backend/src/main/java/com/project/backend/accounts/repository/UserRepository.java
  backend/src/main/java/com/project/backend/accounts/repository/UsersRepository.java
  backend/src/main/java/com/project/backend/accounts/service/UserService.java
  backend/src/main/java/com/project/backend/places/repository/entity/Hotplaces.java
Labels: enhancement

#55 #30 - 로그인 및 회원가입 기능 구현하기
  backend/src/main/java/com/project/backend/accounts/repository/RestaurantReviewRepository.java
  backend/src/main/java/com/project/backend/accounts/repository/UsersRepository.java
  backend/src/main/java/com/project/backend/accounts/repository/entity/RestaurantAdmin.java
  backend/src/main/java/com/project/backend/accounts/repository/entity/RestaurantReview.java
  backend/src/main/java/com/project/backend/accounts/repository/entity/Users.java
  backend/src/main/java/com/project/backend/accounts/service/UserService.java
  backend/src/main/java/com/project/backend/places/repository/entity/Hotplaces.java
Labels: documentation

#57 #30 - 로그인 및 회원가입 기능 구현하기
  backend/src/main/java/com/project/backend/places/service/CulturalEventService.java
  backend/src/main/java/com/project/backend/places/service/CulturalEventServiceImpl.java
  backend/src/main/java/com/project/backend/places/service/HotPlacesService.java
  backend/src/main/java/com/project/backend/places/service/HotPlacesServiceImpl.java
  backend/src/main/java/com/project/backend/places/service/PlaceDistrictService.java
  backend/src/main/java/com/project/backend/places/service/PlaceDistrictServiceImpl.java
  backend/src/main/java/com/project/backend/places/service/PlaceService.java
  backend/src/main/java/com/project/backend/places/service/PlaceServiceImpl.java
  backend/src/main/java/com/project/backend/places/service/PlaceSubwayService.java
  backend/src/main/java/com/project/backend/places/service/PlaceSubwayServiceImpl.java
  backend/src/main/java/com/project/backend/places/service/SubwayService.java
  backend/src/main/java/com/project/backend/places/service/SubwayServiceImpl.java
  backend/src/main/java/com/project/backend/population/service/PopulationServiceImpl.java
  backend/src/main/java/com/project/backend/restaurants/dto/RestaurantDto.java
  backend/src/main/java/com/project/backend/restaurants/repository/entity/Restaurant.java
  backend/src/main/java/com/project/backend/restaurants/service/RestaurantService.java
  backend/src/main/java/com/project/backend/restaurants/service/RestaurantServiceImpl.java
Labels: documentation

#58 #30 - 로그인 및 회원가입 기능 구현하기
  backend/src/main/java/com/project/backend/places/dto/HotplacesDto.java
  backend/src/main/java/com/project/backend/places/service/HotPlacesService.java
Labels: enhancement

#59 #30 - 로그인 및 회원가입 기능 구현하기
  backend/src/main/java/com/project/backend/controller/BoardController.java
Labels: enhancement

#61 #30 - 로그인 및 회원가입 기능 구현하기
  backend/src/main/java/com/project/backend/population/service/PopulationService.java
  backend/src/main/java/com/project/backend/population/service/PopulationServiceImpl.java
  backend/src/main/java/com/project/backend/restaurants/dto/RestaurantDto.java
  backend/src/main/java/com/project/backend/restaurants/repository/entity/Restaurant.java
  backend/src/main/java/com/project/backend/restaurants/service/RestaurantService.java
Labels: enhancement

#65 #30 - 로그인 및 회원가입 기능 구현하기
  backend/src/main/java/com/project/backend/controller/BackendController.java
  backend/src/main/java/com/project/backend/restaurants/dto/RestaurantDto.java
  backend/src/main/java/com/project/backend/restaurants/repository/entity/Restaurant.java
Labels: enhancement

#69 #68-메인페이지 실시간데이터(frontend)
  backend/src/main/frontend/package-lock.json
  backend/src/main/frontend/package.json
Labels: enhancement

#70 #68-메인페이지 실시간데이터(frontend)
  backend/src/main/frontend/build/asset-manifest.json
  backend/src/main/frontend/build/favicon.ico
  backend/src/main/frontend/build/index.html
  backend/src/main/frontend/build/logo192.png
  backend/src/main/frontend/build/logo512.png
  backend/src/main/frontend/build/manifest.json
  backend/src/main/frontend/build/robots.txt
  backend/src/main/frontend/build/static/css/main.e21a7768.css
  backend/src/main/frontend/build/static/css/main.e21a7768.css.map
  backend/src/main/frontend/build/static/js/787.23170c61.chunk.js
  backend/src/main/frontend/build/static/js/787.23170c61.chunk.js.map
  backend/src/main/frontend/build/static/js/main.1d395809.js
  backend/src/main/frontend/build/static/js/main.1d395809.js.LICENSE.txt
  backend/src/main/frontend/build/static/js/main.1d395809.js.map
  backend/src/main/frontend/build/static/media/logo.6ce24c58023cc2f8fd88fe9d219db6c6.svg
Labels: enhancement

#71 #69-FrontEnd-StartFile
  backend/src/main/frontend/public/favicon.ico
  backend/src/main/frontend/public/index.html
  backend/src/main/frontend/public/logo192.png
  backend/src/main/frontend/public/logo512.png
  backend/src/main/frontend/public/manifest.json
  backend/src/main/frontend/public/robots.txt
  backend/src/main/frontend/src/App.css
  backend/src/main/frontend/src/App.js
  backend/src/main/frontend/src/App.test.js
  backend/src/main/frontend/src/AxiosTest.js
  backend/src/main/frontend/src/Header.js
  backend/src/main/frontend/src/Home.js
  backend/src/main/frontend/src/Live.js
  backend/src/main/frontend/src/LiveDetail.js
  backend/src/main/frontend/src/Login.js
  backend/src/main/frontend/src/Predict.js
  backend/src/main/frontend/src/RestaurantPage.js
  backend/src/main/frontend/src/index.css
  backend/src/main/frontend/src/index.js
  backend/src/main/frontend/src/logo.svg
  backend/src/main/frontend/src/reportWebVitals.js
  backend/src/main/frontend/src/setupTests.js
  backend/src/main/java/com/project/backend/configuration/CorsConfig.java
  backend/src/main/java/com/project/backend/controller/BackendController.java
  backend/src/main/java/com/project/backend/controller/BoardController.java
Labels: enhancement

#72 #51 - DetailPageGuideLine
  backend/src/main/java/com/project/backend/controller/LiveContoller.java
  backend/src/main/java/com/project/backend/population/service/PopulationService.java
  backend/src/main/java/com/project/backend/population/service/PopulationServiceImpl.java
Labels: enhancement

#75 Feature/#30 login and signup
  backend/build.gradle
  backend/src/main/java/com/project/backend/SecurityConfig.java
  backend/src/main/java/com/project/backend/accounts/dto/UsersDto.java
  backend/src/main/java/com/project/backend/accounts/form/UserCreateForm.java
  backend/src/main/java/com/project/backend/accounts/repository/UsersRepository.java
  backend/src/main/java/com/project/backend/accounts/repository/entity/Users.java
  backend/src/main/java/com/project/backend/accounts/role/UserRole.java
  backend/src/main/java/com/project/backend/accounts/service/UserSecurityService.java
  backend/src/main/java/com/project/backend/accounts/service/UserService.java
  backend/src/main/java/com/project/backend/configuration/SecurityConfig.java
  backend/src/main/java/com/project/backend/controller/BackendController.java
  backend/src/main/java/com/project/backend/controller/UserController.java
Labels: enhancement

#84 #51-DetailPageGuideLine: Auto stash before merge of "feature/#51-Deta…
  backend/src/main/java/com/project/backend/population/dto/PopulationCongestMsgDto.java
  backend/src/main/java/com/project/backend/population/dto/PopulationDto.java
  backend/src/main/java/com/project/backend/population/service/PopulationService.java
  backend/src/main/java/com/project/backend/population/service/PopulationServiceImpl.java
Labels: enhancement

#87 #31-liveByLocation
  backend/src/main/java/com/project/backend/controller/LiveContoller.java
  backend/src/main/java/com/project/backend/general/returnType/Location.java
  backend/src/main/java/com/project/backend/population/service/PopulationService.java
  backend/src/main/java/com/project/backend/population/service/PopulationServiceImpl.java
Labels: enhancement

#90 gitflow-feature-stash: #89-Login,SignUp,Design
  backend/.gitignore
  backend/src/main/frontend/public/index.html
  backend/src/main/frontend/src/App.css
  backend/src/main/frontend/src/App.js
  backend/src/main/frontend/src/Banner.js
  backend/src/main/frontend/src/Comment.js
  backend/src/main/frontend/src/Header.js
  backend/src/main/frontend/src/Home.js
  backend/src/main/frontend/src/HotplacePage.js
  backend/src/main/frontend/src/Live.js
  backend/src/main/frontend/src/LiveDetail.js
  backend/src/main/frontend/src/Login.js
  backend/src/main/frontend/src/Predict.js
  backend/src/main/frontend/src/RestaurantPage.js
  backend/src/main/frontend/src/SignUp.js
  backend/src/main/frontend/src/test.js
  backend/src/main/java/com/project/backend/accounts/form/UserCreateForm.java
  backend/src/main/java/com/project/backend/controller/BackendController.java
Labels: enhancement

#93 #92-usersEntityModify
  backend/src/main/java/com/project/backend/accounts/dto/UsersDto.java
  backend/src/main/java/com/project/backend/accounts/repository/entity/Users.java
  backend/src/main/java/com/project/backend/controller/BoardController.java
  backend/src/main/java/com/project/backend/controller/UserController.java
  backend/src/main/java/com/project/backend/places/repository/entity/SubwayDetail.java
Labels: bug

#97 Feature/#94 board
  backend/src/main/java/com/project/backend/accounts/dto/HotplaceReviewDto.java
  backend/src/main/java/com/project/backend/accounts/dto/RestaurantReviewDto.java
  backend/src/main/java/com/project/backend/accounts/repository/HotplaceReviewRepository.java
  backend/src/main/java/com/project/backend/accounts/repository/RestaurantReviewRepository.java
  backend/src/main/java/com/project/backend/accounts/repository/UsersRepository.java
  backend/src/main/java/com/project/backend/accounts/repository/entity/HotplaceReview.java
  backend/src/main/java/com/project/backend/accounts/repository/entity/RestaurantReview.java
  backend/src/main/java/com/project/backend/accounts/service/HotplaceReviewService.java
  backend/src/main/java/com/project/backend/accounts/service/HotplaceReviewServiceImpl.java
  backend/src/main/java/com/project/backend/accounts/service/RestaurantReviewService.java
  backend/src/main/java/com/project/backend/accounts/service/RestaurantReviewServiceImpl.java
  backend/src/main/java/com/project/backend/accounts/service/UserService.java
  backend/src/main/java/com/project/backend/controller/BoardController.java
  backend/src/main/java/com/project/backend/places/service/HotPlacesService.java
  backend/src/main/java/com/project/backend/places/service/HotPlacesServiceImpl.java
  backend/src/main/java/com/project/backend/restaurants/repository/RestaurantRepository.java
  backend/src/main/java/com/project/backend/restaurants/repository/entity/Restaurant.java
  backend/src/main/java/com/project/backend/restaurants/service/RestaurantService.java
  backend/src/main/java/com/project/backend/restaurants/service/RestaurantServiceImpl.java
  backend/src/main/java/com/project/backend/security/JwtAuthenticationFilter.java
Labels: enhancement

#99 #51-실시간ByLatitude,Logitude
  backend/gradlew.bat
  backend/src/main/java/com/project/backend/accounts/dto/HotplaceReviewDto.java
  backend/src/main/java/com/project/backend/accounts/dto/UsersDto.java
  backend/src/main/java/com/project/backend/accounts/service/HotplaceReviewService.java
  backend/src/main/java/com/project/backend/controller/BoardController.java
  backend/src/main/java/com/project/backend/controller/CustomErrorController.java
  backend/src/main/java/com/project/backend/controller/LiveContoller.java
  backend/src/main/java/com/project/backend/general/returnType/Location.java
  backend/src/main/java/com/project/backend/places/dto/LogilatiDto.java
  backend/src/main/java/com/project/backend/population/service/PopulationServiceImpl.java
Labels: enhancement

#101 Feature/#95 user register
  backend/src/main/java/com/project/backend/accounts/form/UserCreateForm.java
  backend/src/main/java/com/project/backend/accounts/role/UserRole.java
  backend/src/main/java/com/project/backend/accounts/service/MyPageService.java
  backend/src/main/java/com/project/backend/controller/MyPageController.java
Labels: enhancement

#102 #95-User_register
  backend/src/main/java/com/project/backend/accounts/repository/UsersRepository.java
  backend/src/main/java/com/project/backend/accounts/service/MyPageService.java
Labels: enhancement

#106 Feature/#100 board like
  backend/src/main/java/com/project/backend/accounts/dto/HotplaceLikeDto.java
  backend/src/main/java/com/project/backend/accounts/dto/RestaurantLikeDto.java
  backend/src/main/java/com/project/backend/accounts/repository/HotplaceLikeRepository.java
  backend/src/main/java/com/project/backend/accounts/repository/RestaurantLikeRepository.java
  backend/src/main/java/com/project/backend/accounts/repository/entity/HotplaceLike.java
  backend/src/main/java/com/project/backend/accounts/repository/entity/RestaurantLike.java
  backend/src/main/java/com/project/backend/accounts/service/HotplaceLikeService.java
  backend/src/main/java/com/project/backend/accounts/service/RestaurantLikeService.java
  backend/src/main/java/com/project/backend/controller/BoardController.java
  backend/src/main/java/com/project/backend/controller/LiveContoller.java
  backend/src/main/java/com/project/backend/general/returnType/HotplaceType.java
  backend/src/main/java/com/project/backend/general/returnType/RestaurantType.java
  backend/src/main/java/com/project/backend/places/service/HotPlacesService.java
  backend/src/main/java/com/project/backend/places/service/HotPlacesServiceImpl.java
  backend/src/main/java/com/project/backend/population/service/PopulationServiceImpl.java
  backend/src/main/java/com/project/backend/restaurants/service/RestaurantService.java
  backend/src/main/java/com/project/backend/restaurants/service/RestaurantServiceImpl.java
Labels: enhancement

#110 #109 지하철 승하차인원 예측 모델 관련 EDA 진행
  ML/EDA.ipynb
Labels: enhancement

#111 #85-logUploadCode
  backend/build.gradle
  backend/src/main/java/com/project/backend/controller/LogController.java
  backend/src/main/resources/logback.xml
Labels: enhancement

#114 gitflow-feature-stash: #113-frontend-All
  backend/src/main/frontend/package-lock.json
  backend/src/main/frontend/package.json
  backend/src/main/frontend/public/index.html
  backend/src/main/frontend/src/App.css
  backend/src/main/frontend/src/App.js
  backend/src/main/frontend/src/Banner.js
  backend/src/main/frontend/src/Comment.js
  backend/src/main/frontend/src/CulturePage.js
  backend/src/main/frontend/src/Face.js
  backend/src/main/frontend/src/Header.js
  backend/src/main/frontend/src/Home.js
  backend/src/main/frontend/src/HotplacePage.js
  backend/src/main/frontend/src/Live.js
  backend/src/main/frontend/src/LiveDetail.js
  backend/src/main/frontend/src/Login.js
  backend/src/main/frontend/src/MyPage.js
  backend/src/main/frontend/src/PartnerLogin.js
  backend/src/main/frontend/src/PartnerSignUp.js
  backend/src/main/frontend/src/Predict.js
  backend/src/main/frontend/src/RestaurantPage.js
  backend/src/main/frontend/src/SignUp.js
  backend/src/main/frontend/src/static/IMG_4653.jpg
  backend/src/main/frontend/src/static/IMG_4660.jpg
  backend/src/main/frontend/src/static/배너사진1.jpg
  backend/src/main/frontend/src/static/제목을 입력해주세요_-001 (4).png
  backend/src/main/frontend/src/test.js
  backend/src/main/java/com/project/backend/controller/BoardController.java
Labels: enhancement

#120 #119-RecommendByCategory
  backend/src/main/java/com/project/backend/controller/LiveContoller.java
  backend/src/main/java/com/project/backend/general/returnType/CategoryType.java
  backend/src/main/java/com/project/backend/places/repository/ContentTypeRepository.java
  backend/src/main/java/com/project/backend/places/service/ContentTypeService.java
  backend/src/main/java/com/project/backend/places/service/ContentTypeServiceImpl.java
  backend/src/main/java/com/project/backend/population/service/PopulationService.java
  backend/src/main/java/com/project/backend/population/service/PopulationServiceImpl.java
  backend/src/main/java/com/project/backend/restaurants/repository/RestaurantCategoryRepository.java
  backend/src/main/java/com/project/backend/restaurants/service/RestaurantCategoryService.java
  backend/src/main/java/com/project/backend/restaurants/service/RestaurantCategoryServiceImpl.java
Labels: enhancement

#121 #113-frontend-미래예측페이지수정
  backend/src/main/frontend/src/Predict.js
Labels: enhancement

#122 Feature/#95 user register
  backend/src/main/java/com/project/backend/accounts/dto/UsersDto.java
  backend/src/main/java/com/project/backend/accounts/repository/UsersRepository.java
  backend/src/main/java/com/project/backend/accounts/repository/entity/Users.java
  backend/src/main/java/com/project/backend/accounts/service/MyPageService.java
  backend/src/main/java/com/project/backend/accounts/validator/NicknameFormValidator.java
  backend/src/main/java/com/project/backend/accounts/validator/PasswordFormValidator.java
  backend/src/main/java/com/project/backend/accounts/validator/PhoneNumberFormValidator.java
  backend/src/main/java/com/project/backend/accounts/validator/UserAddressFormValidator.java
  backend/src/main/java/com/project/backend/config/WebSecurityConfig.java
  backend/src/main/java/com/project/backend/controller/MyPageController.java
Labels: enhancement

#123 #95-passwordChange
  backend/src/main/java/com/project/backend/accounts/service/MyPageService.java
  backend/src/main/java/com/project/backend/accounts/service/UserService.java
  backend/src/main/java/com/project/backend/controller/MyPageController.java
Labels: enhancement

#126 #63 데이터 전처리 최종 코드
  ML/Preprocessing.ipynb
Labels: enhancement

#127 #112-지하철 승하차인원 예측 모델링
  ML/modeling_ver0.ipynb
  ML/modeling_ver1.ipynb
  ML/modeling_ver2.ipynb
Labels: enhancement

#130 #124-uploadDocument
  Documents/ERD.png
  Documents/WebAPI.xlsx
  Documents/깃브랜치전략.pdf
  Documents/맛집 크롤링(망고 플레이트) 작업 결과 - 시트1.pdf
  Documents/명소 크롤링(한국관광공사_국문 관광정보 서비스 api) 작업결과 - 시트1.pdf
  Documents/시스템 설계서(초안).pdf
Labels: documentation
